### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamWindell** [book-of-gehn/book-of-gehn.github.io#2]
Great blog!

In "Lock-Free Queue - Part I" there is a line 

> The pointers serve as stop-markers: the producer will not write if the head points to an entry that is immediately before the entry pointed by the head; the consumer will not read if the tail and the head are pointing to the same entry.

I believe 'head' before the semicolon should be changed to 'tail'. Like this:

> The pointers serve as stop-markers: the producer will not write if the head points to an entry that is immediately before the entry pointed by the tail; the consumer will not read if the tail and the head are pointing to the same entry.

**Comment by eldipa** [comment]
You are absolutely right! It is too easy to mess the words and too hard to spot the mistake.

Thanks for taking the time and write the issue (fixed now).
I hope you enjoyed reading the post.

**Comment by SamWindell** [comment]
Thanks! Your article and the comments in the loki library where incredibly helpful with understanding the details of the atomic queue
